name: "Docker build"
permissions:
  id-token: write
  pull-requests: write
  contents: read
  deployments: write
on:
  push:
    branches:
      - NearPrime/mark
jobs:
  docker-build:
    name: Build docker Image
    runs-on: ubuntu-latest
    environment: Sandbox-us-east-1
    #if: github.ref == 'refs/heads/main'
    #needs: sandbox-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1
          role-skip-session-tagging: true
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          # tags: |
          #   ${{ steps.login-ecr.outputs.registry }}/near-for-primelab/rpc:${{ github.sha }}
         